6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Models/GroupViewModel/Group.cs
using System.ComponentModel.DataAnnotations;

namespace RadiostationWeb.Models
{
    public  class Group
    {

        public int Id { get; set; }
        [Required]
        public string Description { get; set; }

    }
}

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Models/GroupViewModel/GroupDetailViewModel.cs
namespace RadiostationWeb.Models
{
    public class GroupDetailViewModel
    {
        public string PerformerName { get; set; }
        public string PerformerSurname { get; set; }
        public string GroupName { get; set; }
    }
}

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Controllers/GroupController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RadiostationWeb.Data;
using RadiostationWeb.Models;
using System.Linq;


namespace RadiostationWeb.Controllers
{
    public class GroupController : Controller
    {
        private readonly RadiostationWebDbContext _dbContext;
        public GroupController(RadiostationWebDbContext context)
        {
            _dbContext = context;
        }

        [Authorize]
        public ActionResult Groups(string groupFilter, int page = 1)
        {
            var pageSize = 10;
            var groups = FilterGroups(groupFilter);
            var pageGroups = groups.OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(groups.Count(), page, pageSize);
            var viewGroups = pageGroups.ToList();

            var pageItemsModel = new PageItemsModel<Group> { Items = viewGroups, PageModel = pageViewModel };
            return View(pageItemsModel);
        }

        [Authorize]
        public ActionResult GroupDetail(int id,int page = 1)
        {
            var pageSize = 10;
            var groupPage = _dbContext.Groups.FirstOrDefault(o => o.Id.Equals(id));

            var groupPerformerDetail = _dbContext.Performers.ToList().Where(o=>o.GroupId.Equals(id));
            var pageDetail = groupPerformerDetail.OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(groupPerformerDetail.Count(), page, pageSize);

            var viewDetails = from p in pageDetail
                              select new GroupDetailViewModel
                              {
                                  PerformerName = p.Name,
                                  PerformerSurname = p.Surname
                              };
            return View(new GroupItemsViewModel {
                GroupsItems = viewDetails,
                GroupName = groupPage.Description,
                PageModel= pageViewModel,
                Id = groupPage.Id
            });
        }

        public IActionResult ResetFilter()
        {

            HttpContext.Response.Cookies.Delete("groupFilter");
            return RedirectToAction(nameof(Groups));

        }
        private IQueryable<Group> FilterGroups(string groupFilter)
        {
            IQueryable<Group> groups = _dbContext.Groups;
            groupFilter = groupFilter ?? HttpContext.Request.Cookies["groupFilter"];
            if (!string.IsNullOrEmpty(groupFilter))
            {
                groups = groups.Where(e => e.Description.Contains(groupFilter));
                HttpContext.Response.Cookies.Append("groupFilter", groupFilter);
            }
            return groups;
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult ManageGroups(int page = 1)
        {
            IQueryable<Group> groups = _dbContext.Groups;
            var pageSize = 10;
            var pageGroups = groups.OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(groups.Count(), page, pageSize);
            var viewGroups = pageGroups.ToList();
            var pageItemsModel = new PageItemsModel<Group> { Items = viewGroups, PageModel = pageViewModel };
            return View(pageItemsModel);
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Delete(int id)
        {
            var group = _dbContext.Groups.Find(id);
            if (group != null)
            {
                try
                {
                    _dbContext.Groups.Remove(group);
                    _dbContext.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home",
                    new { message = "Group contain related data and cannot be deleted" });
                }
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Group not found" });
            }

            return RedirectToAction(nameof(ManageGroups));
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Create()
        {
            return View(new Group());
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        [HttpPost]
        public ActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Groups.Add(group);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(ManageGroups));
            }

            return View(group);
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Edit(int id)
        {
            var group = _dbContext.Groups.Find(id);
            if (group != null)
            {
                return View(group);
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Group not found" });
            }
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        [HttpPost]
        public ActionResult Edit(Group group)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Groups.Update(group);
                if (_dbContext.SaveChanges() != 0)
                {
                    ViewData["SuccessMessage"] = "Information has been successfully edited";
                    return RedirectToAction(nameof(ManageGroups));
                }
            }

            return View(group);
        }

    }
}

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Group/Create.cshtml
@model Group
@{
    ViewData["Title"] = "Create group";
 }
<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Add Group</h1>
        <form asp-action="Create" asp-controller="Group" method="post" class="form">
            <label>Discription</label>
            <input class="inputStyle" asp-for="@Model.Description" type="text" placeholder="Discription">
            <input type="submit" class="addRecordbtn" value="Add">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
        <div class="error-box" asp-validation-summary="All"></div>
    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Group/Edit.cshtml
@model Group
@{
    ViewData["Title"] = "Edit group";
}
<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Edit groups</h1>
        <form asp-action="Edit" asp-controller="Group" method="post" class="form">
            <input asp-for="@Model.Id" type="hidden" />
            <label>Discription</label>
            <input class="inputStyle" asp-for="@Model.Description" type="text" placeholder="Discription">
            <input type="submit" class="addRecordbtn" value="Edit">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
        <div class="error-box" asp-validation-summary="All"></div>
    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Group/GroupDetail.cshtml
@model GroupItemsViewModel
@addTagHelper *, RadiostationWeb

<div class="main-container">
    <div class="container-item">
        <h2 class="title">Group name: @Model.GroupName</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Performer name</th>
                    <th>Performer surname</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var group in @Model.GroupsItems)
                {
                    <tr>
                        <td>@group.PerformerName</td>
                        <td>@group.PerformerSurname</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="pages-container"><page-link page-model="Model.PageModel" model-id="@Model.Id"   page-action="GroupDetail"></page-link></div>
    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Group/Groups.cshtml
@model PageItemsModel<Group>
@addTagHelper *, RadiostationWeb
@{

    ViewData["Title"] = "Groups";

    var groupFilter = (string)Context.Request.Query["groupFilter"] ?? Context.Request.Cookies["groupFilter"];
}
<div class="main-container">
    <div class="info-container">
        <div class="formContainer">
            <h1 class="title">Groups</h1>
            <form asp-action="Groups" asp-controller="Group" method="get" class="form">
                <div class="wrapper-items">
                    <div class="items group-item">
                        <div>Name filter</div>
                        <input class="inputStyle" name="groupFilter" type="text" value="@groupFilter" />
                    </div>

                    <div class="formButtons">
                        <input type="submit" class="addRecordbtn" value="Find">
                        <div class="crudBtn reset"><a class="crudLink" asp-controller="Group" asp-action="ResetFilter"> Reset</a></div>
                    </div>
                </div>
            </form>
        </div>
        <div class="container-item">
            @if (User.IsInRole(RoleType.Admin) || User.IsInRole(RoleType.Employeе))
            {
                <div class="crudBtn"><a class="crudLink" asp-action="ManageGroups" asp-controller="Group">Manage</a></div>
            }
            @if (@Model?.Items.Count() > 0)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var group in @Model.Items)
                        {
                            <tr>
                                <td>
                                    <a asp-controller="Group" asp-action="GroupDetail" asp-route-id="@group.Id">@group.Description</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="pages-container"><page-link page-model="Model.PageModel" page-action="Groups"></page-link></div>
            }
            else
            {
                <h3>There are no Groups </h3>
            }
        </div>

    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Group/ManageGroups.cshtml
@model PageItemsModel<Group>
@addTagHelper *, RadiostationWeb
@{
    ViewData["Title"] = "Manage groups";
}
<div class="main-container">
    <div class="container-item">
        <h1 class="title">Groups management</h1>
    </div>
    <div class="container-item">
        <div class="crudBtn"><a class="crudLink" asp-controller="Group" asp-action="Create"> Add group</a></div>
        @if (@Model?.Items.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Discription</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var group in @Model.Items)
                    {
                        <tr>
                            <td>@group.Description</td>

                            <td>
                                <div class="manage-button-container">
                                    <div class="crudBtn"><a class="crudLink" asp-controller="Group" asp-action="Edit" asp-route-id="@group.Id">Edit</a></div>
                                    <div class="crudBtn"><a class="crudLink" asp-controller="Group" asp-action="Delete" asp-route-id="@group.Id">Delete</a></div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="pages-container"><page-link page-model="Model.PageModel" page-action="ManageGroups"></page-link></div>
        }
        else
        {
            <h3>There are no groups</h3>
        }

    </div>
</div>