6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Models/RecordViewModel/Record.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RadiostationWeb.Models
{
    public partial class Record
    {
        public int Id { get; set; }
        [Required]
        public int PerformerId { get; set; }
        [Required]
        public int GenreId { get; set; }
        [Required]
        public string Album { get; set; }
        [Required]
        public DateTime RecordDate { get; set; }
        [Required]
        public int Lasting { get; set; }
        [Required]
        public decimal Rating { get; set; }
        [Required]
        public string СompositionName { get; set; }

    }
}

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Models/RecordViewModel/RecordViewModel.cs
using System;


namespace RadiostationWeb.Models
{
    public class RecordViewModel
    {
        public int Id { get; set; }
        public int GenreId { get; set; }
        public string PerformerName { get; set; }
        public string GenreName { get; set; }

        public string Album { get; set; }
        public DateTime RecordDate { get; set; }
        public int Lasting { get; set; }
        public decimal Rating { get; set; }
        public string СompositionName { get; set; }
}
}

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Controllers/RecordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RadiostationWeb.Data;
using RadiostationWeb.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RadiostationWeb.Controllers
{
    public class RecordController : Controller
    {
        private readonly RadiostationWebDbContext _dbContext;
        public RecordController(RadiostationWebDbContext context)
        {
            _dbContext = context;
        }
        [Authorize]
        public async Task<ActionResult> Records(string nameFilter, int? performerFilter, int page = 1)
        {
            var pageSize = 10;
            var records = FilterRecords(nameFilter, performerFilter);
            var performers = await _dbContext.Performers.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name + " " + c.Surname })
            .ToListAsync();
            var pageRecords = records.OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(records.Count(), page, pageSize);
            var viewRecords = pageRecords.ToList().Join(_dbContext.Performers.ToList(),
            e => e.PerformerId, t => t.Id,
            (e, t) => new RecordViewModel
            {
                Id = e.Id,
                PerformerName = t.Name,
                GenreId = e.GenreId,
                Album = e.Album,
                RecordDate = (e.RecordDate),
                Lasting = e.Lasting,
                Rating = e.Rating,
                СompositionName = e.СompositionName
            }).Join(_dbContext.Genres.ToList(), e => e.GenreId, t => t.Id,
            (e, t) => new RecordViewModel
            {
                Id = e.Id,
                PerformerName = e.PerformerName,
                GenreName = t.GenreName,
                Album = e.Album,
                RecordDate = e.RecordDate,
                Lasting = e.Lasting,
                Rating = e.Rating,
                СompositionName = e.СompositionName
            }
            );
            var pageItemsModel = new RecordsItemModel { Items = viewRecords, PageModel = pageViewModel, SelectPerformers = performers };
            return View(pageItemsModel);
        }

        public IActionResult ResetFilter()
        {

            HttpContext.Response.Cookies.Delete("nameFilter");
            HttpContext.Response.Cookies.Delete("performerFilter");
            return RedirectToAction(nameof(Records));
        }

        public IActionResult ResetManageFilter()
        {

            HttpContext.Response.Cookies.Delete("nameFilter");
            HttpContext.Response.Cookies.Delete("performerFilter");
            return RedirectToAction(nameof(ManageRecords));
        }
        private IQueryable<Record> FilterRecords(string nameFilter, int? performerFilter)
        {
            IQueryable<Record> records = _dbContext.Records;
            nameFilter = nameFilter ?? HttpContext.Request.Cookies["nameFilter"];
            if (!string.IsNullOrEmpty(nameFilter))
            {
                records = records.Where(e => e.СompositionName.Contains(nameFilter));
                HttpContext.Response.Cookies.Append("nameFilter", nameFilter);
            }
            int cookiePerformerFilter;
            int.TryParse(HttpContext.Request.Cookies["performerFilter"], out cookiePerformerFilter);
            performerFilter = performerFilter ?? cookiePerformerFilter;
            if (performerFilter != 0)
            {
                records = records.Where(e => e.PerformerId == performerFilter);
                HttpContext.Response.Cookies.Append("performerFilter", performerFilter.ToString());
            }
            return records;
        }


        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult ManageRecords(string nameFilter, int? performerFilter, int page = 1)
        {
            var pageSize = 10;
            var records = FilterRecords(nameFilter, performerFilter);
            var performers = _dbContext.Performers.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name+" " + c.Surname })
            .ToList();
            var pageRecords = records.ToList().OrderByDescending(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(records.Count(), page, pageSize);
            var viewRecords = pageRecords.ToList().Join(_dbContext.Performers.ToList(),
            e => e.PerformerId, t => t.Id,
            (e, t) => new RecordViewModel
            {
                Id = e.Id,
                PerformerName = t.Name,
                GenreId = e.GenreId,
                Album = e.Album,
                RecordDate = (e.RecordDate),
                Lasting = e.Lasting,
                Rating = e.Rating,
                СompositionName = e.СompositionName
            }).Join(_dbContext.Genres.ToList(), e => e.GenreId, t => t.Id,
            (e, t) => new RecordViewModel
            {
                Id = e.Id,
                PerformerName = e.PerformerName,
                GenreName = t.GenreName,
                Album = e.Album,
                RecordDate = e.RecordDate,
                Lasting = e.Lasting,
                Rating = e.Rating,
                СompositionName = e.СompositionName
            }
            );
            var pageItemsModel = new RecordsItemModel { Items = viewRecords, PageModel = pageViewModel, SelectPerformers = performers };
            return View(pageItemsModel);
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Delete(int id)
        {
            var record = _dbContext.Records.Find(id);
            if (record != null)
            {
                try
                {
                    _dbContext.Records.Remove(record);
                    _dbContext.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home",
                    new { message = "Record contain related data and cannot be deleted" });
                }
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Record not found" });
            }

            return RedirectToAction(nameof(ManageRecords));
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Create()
        {
            var performers = _dbContext.Performers.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name+" "+c.Surname })
            .ToList();

            var genres = _dbContext.Genres.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.GenreName })
            .ToList();
            return View(new CreateRecordViewModel { PerformersList = performers, GenresList = genres });
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        [HttpPost]
        public ActionResult Create(CreateRecordViewModel record)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Records.Add(new Record
                {
                    СompositionName = record.СompositionName,
                    Album = record.Album,
                    GenreId = record.GenreId,
                    Lasting = record.Lasting,
                    Rating = record.Rating,
                    RecordDate = record.RecordDate,
                    PerformerId = record.PerformerId
                });
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(ManageRecords));
            }
            var performers = _dbContext.Performers.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name+" "+ c.Surname })
            .ToList();

            var genres = _dbContext.Genres.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.GenreName })
            .ToList();

            record.GenresList = genres;
            record.PerformersList = performers;

            return View(record);
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        public ActionResult Edit(int id)
        {
            var record = _dbContext.Records.Find(id);
            var performers = _dbContext.Performers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name + " " + c.Surname,
                Selected = record.PerformerId == c.Id
            }).ToList();

            var genres = _dbContext.Genres.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.GenreName,
                Selected = record.GenreId == c.Id
            }).ToList();
            if (record != null)
            {
                return View(new EditRecordViewModel
                {
                    Id = id,
                    PerformersList = performers,
                    GenresList = genres,
                    Album = record.Album,
                    GenreId = record.GenreId,
                    PerformerId = record.PerformerId,
                    RecordDate = record.RecordDate,
                    Lasting = record.Lasting,
                    Rating = record.Rating,
                    СompositionName = record.СompositionName
                });
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Record not found" });
            }
        }

        [AuthorizeRoles(RoleType.Admin, RoleType.Employeе)]
        [HttpPost]
        public async Task<ActionResult> Edit(EditRecordViewModel record)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Records.Update(new Record
                {
                    Id = record.Id,

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Record/Create.cshtml
@model CreateRecordViewModel
<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Add record</h1>
        <div class="error-box" asp-validation-summary="All"></div>
        <form asp-action="Create" asp-controller="Record" method="post" class="form">
            <label>Composition name</label>
            <input class="inputStyle" asp-for="@Model.СompositionName" type="text" placeholder="Composition name">
            <label>Album</label>
            <input class="inputStyle" asp-for="@Model.Album" type="text" placeholder="Album">
            <div class="select-container">
                <label>Performer</label>
                <select class="select-items" asp-for="@Model.PerformerId" asp-items="@Model.PerformersList" required> <option value="" disabled selected>Select  Performer</option></select>
                <label>Genre</label>
                <select class="select-items" asp-for="@Model.GenreId" asp-items="@Model.GenresList" required> <option value="" disabled selected>Select  Genre</option></select>
            </div>
            <label>Lasting</label>
            <input class="inputStyle" asp-for="@Model.Lasting" type="number" min="60" placeholder="Lasting">
            <label>Rating</label>
            <input class="inputStyle" asp-for="@Model.Rating" type="number" step="0.1" min="1" max="5" placeholder="Rating ">
            <label>Record date</label>
            <input class="inputStyle" asp-for="@Model.RecordDate" type="date" min="1960-01-01" value="2000-01-01" placeholder="Record date">
            <input type="submit" class="addRecordbtn" value="Add">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Record/Edit.cshtml
@model EditRecordViewModel
@{
    ViewData["Title"] = "Edit records";

}

<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Edit records</h1>
        <div class="error-box" asp-validation-summary="All"></div>
        <form asp-action="Edit" asp-controller="Record" method="post" class="form">
            <input asp-for="@Model.Id" type="hidden" />
            <label>Composition name</label>
            <input class="inputStyle" asp-for="@Model.СompositionName" type="text" placeholder="Composition name">
            <label>Album</label>
            <input class="inputStyle" asp-for="@Model.Album" type="text" placeholder="Album">
            <div class="select-container">
                <label>Performer</label>
                <select class="select-items" asp-for="@Model.PerformerId" asp-items="@Model.PerformersList" required>
                    <option value="" disabled>Select Performer</option>
                </select>
                <label>Genre</label>
                <select class="select-items" asp-for="@Model.GenreId" asp-items="@Model.GenresList" required>
                    <option value="" disabled>Select Genre</option>
                </select>
            </div>
            <label>Lasting</label>
            <input class="inputStyle" asp-for="@Model.Lasting" min="60" type="number" placeholder="Lasting">
            <label>Rating</label>
            <input class="inputStyle" asp-for="@Model.Rating" type="number" step="0.1" min="1" max="5" placeholder="Rating ">
            <label>Record date</label>
            <input class="inputStyle" asp-for="@Model.RecordDate" type="date" min="1960-01-01" placeholder="Record date">
            <input type="submit" class="addRecordbtn" value="Edit">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Record/ManageRecords.cshtml
@model RecordsItemModel
@addTagHelper *, RadiostationWeb

@{
    ViewData["Title"] = "Manage records";
    var currentNameFilter = (string)Context.Request.Query["nameFilter"] ?? Context.Request.Cookies["nameFilter"];
}
<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Records managment</h1>
        <form asp-action="ManageRecords" asp-controller="Record" method="get" class="form">
            <div class="wrapper-items">
                <div class="items">
                    <div>Name filter</div>
                    <input class="inputStyle" name="nameFilter" type="text" value="@currentNameFilter" />
                </div>
                <div class="items">
                    <div>Performer filter</div>
                    <select class="select-items" name="performerFilter" asp-items="@Model.SelectPerformers">
                        <option value="" disabled selected>Select  Performer</option>
                    </select>
                </div>
            </div>
            <div class="formButtons">
                <input type="submit" class="addRecordbtn" value="Find">
                <div class="crudBtn reset"><a class="crudLink" asp-controller="Record" asp-action="ResetManageFilter"> Reset</a></div>
            </div>
        </form>
    </div>
    <div class="container-item">
        <div class="crudBtn"><a class="crudLink" asp-controller="Record" asp-action="Create"> Add record</a></div>
        @if (@Model?.Items.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Composition name</th>
                        <th>Album</th>
                        <th>Genre name</th>
                        <th>Performer name</th>
                        <th>Lasting</th>
                        <th>Rating</th>
                        <th>Record date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var records in @Model.Items)
                    {
                        <tr>
                            <td>@records.СompositionName</td>
                            <td>@records.Album</td>
                            <td>@records.GenreName</td>
                            <td>@records.PerformerName</td>
                            <td>@records.Lasting</td>
                            <td>@records.Rating</td>
                            <td>@records.RecordDate.ToShortDateString()</td>
                            <td>
                                <div class="manage-button-container">
                                    <div class="crudBtn"><a class="crudLink" asp-controller="Record" asp-action="Edit" asp-route-id="@records.Id">Edit</a></div>
                                    <div class="crudBtn"><a class="crudLink" asp-controller="Record" asp-action="Delete" asp-route-id="@records.Id">Delete</a></div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="pages-container"><page-link page-model="Model.PageModel" page-action="Records"></page-link></div>
        }
        else
        {
            <h3>There are no records</h3>
        }

    </div>
</div>

6sem/OTPO/CourseWorkDB-main/Radiostation/RadiostationWeb/Views/Record/Records.cshtml
@model RecordsItemModel
@addTagHelper *, RadiostationWeb
@{
    ViewData["Title"] = "Records";

    var currentNameFilter = (string)Context.Request.Query["nameFilter"] ?? Context.Request.Cookies["nameFilter"];
}

<div class="main-container">
    <div class="formContainer">
        <h1 class="title">Records</h1>
        <form asp-action="Records" asp-controller="Record" method="get" class="form">
            <div class="wrapper-items">
                <div class="items">
                    <div>Composition name filter</div>
                    <input class="inputStyle" name="nameFilter" type="text" value="@currentNameFilter" />
                </div>
                <div class="items">
                    <div>Performer filter</div>
                    <select class="select-items" name="performerFilter" asp-items="@Model.SelectPerformers">
                        <option value="" disabled selected>Select Performer</option>
                    </select>
                </div>
            </div>
            <div class="formButtons">
                <input type="submit" class="addRecordbtn" value="Find">
                <div class="crudBtn reset"><a class="crudLink" asp-controller="Record" asp-action="ResetFilter"> Reset</a></div>
            </div>
        </form>
    </div>
    <div class="container-item">

        @if (User.IsInRole(RoleType.Admin) || User.IsInRole(RoleType.Employeе))
        {
            <div class="crudBtn"><a class="crudLink" asp-action="ManageRecords" asp-controller="Record">Manage</a></div>
        }
        @if (@Model?.Items?.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Composition name</th>
                        <th>Album</th>
                        <th>Genre name</th>
                        <th>Performer name</th>
                        <th>Lasting</th>
                        <th>Rating</th>
                        <th>Record date</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var record in Model.Items)
                    {
                        <tr>
                            <td>@record.СompositionName</td>
                            <td>@record.Album</td>
                            <td>@record.GenreName</td>
                            <td>@record.PerformerName</td>
                            <td>@record.Lasting</td>
                            <td>@record.Rating</td>
                            <td>@record.RecordDate.ToShortDateString()</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="pages-container"><page-link page-model="Model.PageModel" page-action="Records"></page-link></div>
        }
        else
        {
            <h3>There are no records</h3>
        }

    </div>
</div>