5sem/DataBases/lab5/RadiostationWeb/Models/Genre.cs
using System.Collections.Generic;

#nullable disable

namespace RadiostationWeb.Models
{
    public partial class Genre
    {
        public Genre()
        {
            Records = new HashSet<Record>();
        }

        public int Id { get; set; }
        public string GenreName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Record> Records { get; set; }
    }
}

5sem/DataBases/lab5/RadiostationWeb/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RadiostationWeb.Data;
using RadiostationWeb.Models;

using System.Linq;


namespace RadiostationWeb.Controllers
{
    public class GenreController : Controller
    {
        private readonly BDLab1Context _dbContext;
        public GenreController(BDLab1Context context)
        {
            _dbContext = context;
        }


        [Authorize]
        public ActionResult Genres(string genreNameFilter, int page = 1)
        {
            var pageSize = 20;
            var genres = FilterGenres(genreNameFilter);
            var pageGenres = genres.OrderBy(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(genres.Count(), page, pageSize);
            var viewGenres = pageGenres.ToList();

            var pageItemsModel = new PageItemsModel<Genre> { Items = viewGenres, PageModel = pageViewModel };
            return View(pageItemsModel);
        }

        public IActionResult ResetFilter()
        {

            HttpContext.Response.Cookies.Delete("genreNameFilter");
            return RedirectToAction(nameof(Genres));

        }
        private IQueryable<Genre> FilterGenres(string genreNameFilter)
        {
            IQueryable<Genre> genres = _dbContext.Genres;
            genreNameFilter = genreNameFilter ?? HttpContext.Request.Cookies["genreNameFilter"];
            if (!string.IsNullOrEmpty(genreNameFilter))
            {
                genres = genres.Where(e => e.Description.Contains(genreNameFilter));
                HttpContext.Response.Cookies.Append("genreNameFilter", genreNameFilter);
            }


            if (genreNameFilter == " ")
            {
                genres = _dbContext.Genres;
            }
            return genres;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ManageGenres(int page = 1)
        {
            IQueryable<Genre> genres = _dbContext.Genres;
            var pageSize = 20;
            var pageGenres = genres.OrderBy(o => o.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageViewModel pageViewModel = new PageViewModel(genres.Count(), page, pageSize);
            var viewGenres = pageGenres.ToList();
            var pageItemsModel = new PageItemsModel<Genre> { Items = viewGenres, PageModel = pageViewModel };
            return View(pageItemsModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var genre = _dbContext.Genres.Find(id);
            if (genre != null)
            {
                try
                {
                    _dbContext.Genres.Remove(genre);
                    _dbContext.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home",
                    new { message = "Genre contain related data and cannot be deleted" });
                }
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Genre not found" });
            }

            return RedirectToAction("ManageGenres");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View(new Genre());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Genres.Add(genre);
                _dbContext.SaveChanges();
                return RedirectToAction("ManageGenres");
            }

            return View(genre);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var genre = _dbContext.Genres.Find(id);
            if (genre != null)
            {
                return View(genre);
            }
            else
            {
                return RedirectToAction("Error", "Home",
                    new { message = "Genre not found" });
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Genres.Update(genre);
                if (_dbContext.SaveChanges() != 0)
                {
                    ViewData["SuccessMessage"] = "Information has been successfully edited";
                    return RedirectToAction(nameof(ManageGenres));
                }
            }

            return View(genre);
        }
    }
}

5sem/DataBases/lab5/RadiostationWeb/Views/Genre/Create.cshtml
@model Genre
<div class="all-container">
    <div class="formContainer">
        <h1 class="title">Add genre</h1>
        <form asp-action="Create" asp-controller="Genre" method="post" class="form">
            <label>Genre name</label>
            <input class="inputStyle" asp-for="@Model.GenreName" type="text" placeholder="Genre name">
            <label>Discription</label>
            <input class="inputStyle" asp-for="@Model.Description" type="text" placeholder="Description">           
            <input type="submit" class="addRecordbtn" value="Add">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
        <div class="error-box" asp-validation-summary="All"></div>
    </div>
</div>

5sem/DataBases/lab5/RadiostationWeb/Views/Genre/Edit.cshtml
@model Genre
<div class="all-container">
    <div class="formContainer">
        <h1 class="title">Edit genre</h1>
        <form asp-action="Edit" asp-controller="Genre" method="post" class="form">
            <input asp-for="@Model.Id" type="hidden" />
            <label>Genre name</label>
            <input class="inputStyle" asp-for="@Model.GenreName" type="text" placeholder="Genre name">
            <label>Description</label>
            <input class="inputStyle" asp-for="@Model.Description" type="text" placeholder="Description">
            <input type="submit" class="addRecordbtn" value="Edit">
        </form>
        <p class="success-message">@ViewData["SuccessMessage"]</p>
        <div class="error-box" asp-validation-summary="All"></div>
    </div>
</div>

5sem/DataBases/lab5/RadiostationWeb/Views/Genre/Genres.cshtml
@model PageItemsModel<Genre>
@addTagHelper *, RadiostationWeb
<div class="all-container">
    <div class="container-item">
        <h1 class="title">Genres</h1>
        @if (User.Identity.IsAuthenticated && User.IsInRole(RoleType.Admin))
        {
            <div class="crudBtn"><a class="crudLink" asp-action="ManageGenres" asp-controller="Genre">Manage</a></div>
        }
        @if (@Model?.Items.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Genre name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var genre in @Model.Items)
                    {
                        <tr>
                            <td>@genre.GenreName</td>
                            <td>@genre.Description</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3>There are no genres </h3>
        }
        <div class="pages-container"><page-link page-model="Model.PageModel" page-action="Genres"></page-link></div>
    </div>
</div>

5sem/DataBases/lab5/RadiostationWeb/Views/Genre/ManageGenres.cshtml
@model PageItemsModel<Genre>
@addTagHelper *, RadiostationWeb
<div class="all-container">
    <div class="container-item">
        <h1 class="title">Genres management</h1>
    </div>
    <div class="container-item">
        @if (@Model?.Items.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Genre name</th>
                        <th>Discription</th>
                        <th><div class="manage-button-container"><div class="crudBtn"><a class="crudLink" asp-controller="Genre" asp-action="Create"> Add genre</a></div></div></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var genre in @Model.Items)
                    {
                    <tr>
                        <td>@genre.GenreName</td>
                        <td>@genre.Description</td>
                        <td>
                            <div class="manage-button-container">
                                <div class="crudBtn"><a class="crudLink" asp-controller="Genre" asp-action="Edit" asp-route-id="@genre.Id">Edit</a></div>
                                <div class="crudBtn"><a class="crudLink" asp-controller="Genre" asp-action="Delete" asp-route-id="@genre.Id">Delete</a></div>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3>There are no genres</h3>
        }
        <div class="pages-container"><page-link page-model="Model.PageModel" page-action="Genre"></page-link></div>
    </div>
</div>